global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.EntityFrameworkCore;
global using DBro.Web.Handlers;
global using DBro.Shared;
global using DBro.Shared.Extensions;
global using DBro.Shared.Models;
global using DBro.Web.Components.Layout;
global using DBro.Web.Components.Pages;
global using DBro.Web.Services;
global using DBro.Web.Validators;
global using static DBro.Shared.Extensions.Utilities;